Add Magento projects to project type mapping
mediact/testing-suite pull request #66
Opened 2021-03-24 07:20 UTC by ArjenMiedema

To make it easier to install the testing suite for Magento, it's
now possible to set the project type in the project's composer.json
file to `magento2-project` or `magento-project` to get the correct
coding standards files in the project.

2021-03-24 16:06 UTC, leonhelmus approved these changes

2021-03-24 16:08 UTC, leonhelmus commented
Looks good i have also tested it. Just waiting for an approval of @marcelmediact .

2021-03-25 07:46 UTC, ksangers requested changes

2021-03-25 07:46 UTC, ksangers commented on src/ProjectTypeResolver.php
> +        // Fallback to the "old" solution
This is not the fallback. This is the way to allow it to be configured (and overridden). Basing the testing-suite on the "type" is the fallback, even though it is very useful. Please remove or reflect this in the comment.

2021-03-25 07:47 UTC, ksangers commented
@ArjenMiedema I'm afraid a small change is required.

2021-03-25 07:48 UTC, ksangers commented
@ArjenMiedema I'm afraid I have a small request for change. To prevent it from being removed in the future.

2021-03-25 13:05 UTC, ArjenMiedema commented on src/ProjectTypeResolver.php
> +        // Fallback to the "old" solution
True, that was an incorrect comment here. Removed it.

2021-03-25 13:11 UTC, ksangers approved these changes

2021-03-25 13:13 UTC, merged